Errors display if password and confirm password don't match when resetting password
Baonganbui123/Ngan_Testcases_Set1 pull request #13
Opened 2021-09-06 09:24 UTC by Baonganbui123

2021-09-06 09:57 UTC, MinhQuan119 commented on src/test/java/tests/ForgotPasswordTests.java
> +        forgotPasswordPage.clickForgotPasswordLink();
![image](https://user-images.githubusercontent.com/23515968/132198981-2dc67bc5-f9b9-4a7c-b3ce-cd21b905fcdb.png)

clickForgotPasswordLink method belongs to LoginPage class, not ForgotPasswordPage class

2021-09-06 10:07 UTC, Baonganbui123 commented on src/test/java/tests/ForgotPasswordTests.java
> +        forgotPasswordPage.clickForgotPasswordLink();
I changed it, please check again!

2021-09-06 10:11 UTC, MinhQuan119 commented on src/main/java/page_object/LoginPage.java
> +
redundant

2021-09-06 10:26 UTC, Baonganbui123 commented on src/main/java/page_object/LoginPage.java
> +
Done, please check again!

2021-09-06 10:40 UTC, MinhQuan119 approved these changes

2021-09-06 12:16 UTC, tanmle requested changes

2021-09-06 12:16 UTC, tanmle commented on src/main/java/page_object/LoginPage.java
> +    private WebElement getForgotPassword() {
getLnk...

2021-09-06 12:16 UTC, tanmle commented on src/test/java/tests/ForgotPasswordTests.java
> +        Assert.fail();
why don't you put a message for `Assert.fail`?

2021-09-06 12:16 UTC, tanmle commented on src/test/java/tests/ForgotPasswordTests.java
> +        LogHelpers.printInfo("Verify that error page displayed when click send instructions button");
We are not verifying the error page, the error page is unexpected.

2021-09-06 14:04 UTC, Baonganbui123 commented on src/main/java/page_object/LoginPage.java
> +    private WebElement getForgotPassword() {
I fixed it, please check again.

2021-09-06 15:04 UTC, Baonganbui123 commented on src/test/java/tests/ForgotPasswordTests.java
> +        Assert.fail();
I putted a message for Assert.fail(), please check again!

2021-09-06 15:04 UTC, Baonganbui123 commented on src/test/java/tests/ForgotPasswordTests.java
> +        LogHelpers.printInfo("Verify that error page displayed when click send instructions button");
I fixed it, please check again!

2021-09-07 01:20 UTC, tanmle approved these changes

2021-09-07 01:20 UTC, merged